// docs/.vitepress/theme/components/SidebarNav.vue
<script setup lang="ts">
import { BookOpen, Box, Search, X } from "@lucide/vue";
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { useRoute, withBase } from "vitepress";

import { COMPONENT_DIRECTORY_LINKS } from "../../../src/data/component-directory";
import { trapTabFocus } from "../focus";
import { isNavigationPathActive, SITE_NAVIGATION_LINKS } from "../navigation";

const props = withDefaults(
  defineProps<{
    mobileOpen: boolean;
    mode?: "docs" | "site";
  }>(),
  {
    mode: "docs",
  },
);

const emit = defineEmits<{
  close: [];
}>();

const route = useRoute();
const componentQuery = ref("");
const sidebar = ref<HTMLElement | null>(null);
const searchInput = ref<HTMLInputElement | null>(null);
let mobileViewport: MediaQueryList | null = null;

const documentGroups = [
  {
    label: "Getting started",
    links: [
      { href: "/docs/", text: "Introduction" },
      { href: "/docs/installation", text: "Installation" },
      { href: "/docs/registry", text: "Registry" },
    ],
  },
  {
    label: "Foundation",
    links: [{ href: "/docs/design-tokens", text: "Design tokens" }],
  },
];

const siteGroups = [
  {
    label: "Explore",
    links: SITE_NAVIGATION_LINKS,
  },
  {
    label: "Project",
    links: [
      { href: "/docs/stars", text: "Stars data" },
      { href: "/docs/resources", text: "Resources" },
      { href: "/docs/credits", text: "Credits & license" },
    ],
  },
];

const navigationLabel = computed(() =>
  props.mode === "site" ? "Site navigation" : "Documentation navigation",
);

const projectLinks = [
  { href: "/docs/stars", text: "Stars" },
  { href: "/docs/resources", text: "Resources" },
  { href: "/docs/credits", text: "Credits & license" },
];

const filteredComponents = computed(() => {
  const query = componentQuery.value.trim().toLowerCase();
  if (!query) return COMPONENT_DIRECTORY_LINKS;
  return COMPONENT_DIRECTORY_LINKS.filter((link) => link.text.toLowerCase().includes(query));
});

function isActive(href: string) {
  return isNavigationPathActive(route.path, href);
}

function setBackgroundInert(inert: boolean) {
  const selectors =
    props.mode === "site"
      ? [".site-header", "#main-content"]
      : [".site-header", ".docs-main", ".docs-toc"];
  for (const selector of selectors) {
    document.querySelector<HTMLElement>(selector)?.toggleAttribute("inert", inert);
  }
}

function onViewportChange(event: MediaQueryListEvent) {
  if (!event.matches && props.mobileOpen) {
    emit("close");
  }
}

async function closeAndRestoreFocus() {
  emit("close");
  await nextTick();
  document.querySelector<HTMLButtonElement>(".mobile-menu-button")?.focus();
}

function onSidebarKeydown(event: KeyboardEvent) {
  if (!props.mobileOpen) return;

  if (event.key === "Escape") {
    event.preventDefault();
    void closeAndRestoreFocus();
    return;
  }

  trapTabFocus(event);
}

async function revealActiveLink() {
  await nextTick();

  const container = sidebar.value;
  const activeLink = container?.querySelector<HTMLElement>('a[aria-current="page"]');
  if (!container || !activeLink) return;

  const containerRect = container.getBoundingClientRect();
  const activeRect = activeLink.getBoundingClientRect();
  const edgePadding = 24;
  const isVisible =
    activeRect.top >= containerRect.top + edgePadding &&
    activeRect.bottom <= containerRect.bottom - edgePadding;

  if (!isVisible) {
    container.scrollTo({
      top:
        container.scrollTop +
        activeRect.top -
        containerRect.top -
        containerRect.height / 2 +
        activeRect.height / 2,
    });
  }
}

onMounted(() => {
  void revealActiveLink();
  mobileViewport = window.matchMedia("(max-width: 1023px)");
  mobileViewport.addEventListener("change", onViewportChange);
  if (!mobileViewport.matches && props.mobileOpen) {
    emit("close");
  }
});

watch(
  () => props.mobileOpen,
  async (open) => {
    if (typeof document !== "undefined") {
      document.documentElement.classList.toggle("menu-open", open);
      setBackgroundInert(open);
    }
    if (open) {
      await nextTick();
      if (props.mode === "docs") {
        searchInput.value?.focus();
      } else {
        sidebar.value?.querySelector<HTMLAnchorElement>(".docs-nav a")?.focus();
      }
    }
  },
);

watch(
  () => route.path,
  async () => {
    emit("close");
    await revealActiveLink();
  },
);

onBeforeUnmount(() => {
  mobileViewport?.removeEventListener("change", onViewportChange);
  document.documentElement.classList.remove("menu-open");
  setBackgroundInert(false);
});
</script>

<template>
  <button
    v-if="mobileOpen"
    class="sidebar-scrim"
    type="button"
    :aria-label="`Close ${navigationLabel.toLowerCase()}`"
    @click="closeAndRestoreFocus"
  />

  <aside
    ref="sidebar"
    class="docs-sidebar"
    :class="{
      'docs-sidebar--site': props.mode === 'site',
      'is-open': mobileOpen,
    }"
    :aria-label="navigationLabel"
    :role="mobileOpen ? 'dialog' : undefined"
    :aria-modal="mobileOpen ? 'true' : undefined"
    @keydown="onSidebarKeydown"
  >
    <div class="docs-sidebar__mobile-head">
      <strong>{{ props.mode === "site" ? "Browse site" : "Browse docs" }}</strong>
      <button
        class="icon-button"
        type="button"
        aria-label="Close navigation"
        @click="closeAndRestoreFocus"
      >
        <X :size="18" :stroke-width="2.4" />
      </button>
    </div>

    <nav class="docs-nav">
      <template v-if="props.mode === 'site'">
        <section v-for="group in siteGroups" :key="group.label" class="docs-nav__group">
          <h2>
            <BookOpen :size="13" />
            {{ group.label }}
          </h2>
          <a
            v-for="link in group.links"
            :key="link.href"
            :aria-current="isActive(link.href) ? 'page' : undefined"
            :class="{ 'is-active': isActive(link.href) }"
            :href="withBase(link.href)"
          >
            {{ link.text }}
          </a>
        </section>
      </template>

      <template v-else>
        <section class="docs-nav__group docs-nav__mobile-site">
          <h2>
            <BookOpen :size="13" />
            Explore site
          </h2>
          <a
            v-for="link in SITE_NAVIGATION_LINKS"
            :key="link.href"
            :aria-current="isActive(link.href) ? 'page' : undefined"
            :class="{ 'is-active': isActive(link.href) }"
            :href="withBase(link.href)"
          >
            {{ link.text }}
          </a>
        </section>

        <section v-for="group in documentGroups" :key="group.label" class="docs-nav__group">
          <h2>
            <BookOpen :size="13" />
            {{ group.label }}
          </h2>
          <a
            v-for="link in group.links"
            :key="link.href"
            :aria-current="isActive(link.href) ? 'page' : undefined"
            :class="{ 'is-active': isActive(link.href) }"
            :href="withBase(link.href)"
          >
            {{ link.text }}
          </a>
        </section>

        <section class="docs-nav__group docs-nav__components">
          <div class="docs-nav__group-heading">
            <h2>
              <Box :size="13" />
              Components
            </h2>
            <span>{{ filteredComponents.length }}/{{ COMPONENT_DIRECTORY_LINKS.length }}</span>
          </div>

          <label class="sidebar-filter">
            <Search :size="14" aria-hidden="true" />
            <input
              ref="searchInput"
              v-model="componentQuery"
              type="search"
              placeholder="Filter components"
              aria-label="Filter components"
            />
          </label>

          <div class="component-nav-list">
            <a
              v-for="link in filteredComponents"
              :key="link.href"
              :aria-current="isActive(link.href) ? 'page' : undefined"
              :class="{ 'is-active': isActive(link.href) }"
              :href="withBase(link.href)"
            >
              {{ link.text }}
            </a>
            <p v-if="filteredComponents.length === 0" class="component-nav-empty">No matches</p>
          </div>
        </section>

        <section class="docs-nav__group">
          <h2>Project</h2>
          <a
            v-for="link in projectLinks"
            :key="link.href"
            :aria-current="isActive(link.href) ? 'page' : undefined"
            :class="{ 'is-active': isActive(link.href) }"
            :href="withBase(link.href)"
          >
            {{ link.text }}
          </a>
        </section>
      </template>
    </nav>
  </aside>
</template>

// docs/src/site/components/sidebar-nav.tsx
"use client";

import { Link, useRouter } from "fumapress/client";
import { BookOpen, Box, Search, X } from "lucide-react";
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";

import { COMPONENT_DIRECTORY_LINKS } from "@/data/component-directory";
import { trapTabFocus } from "@/site/lib/focus";
import { isNavigationPathActive, SITE_NAVIGATION_LINKS } from "@/site/lib/navigation";

const documentGroups = [
  {
    label: "Getting started",
    links: [
      { href: "/docs", text: "Introduction" },
      { href: "/docs/installation", text: "Installation" },
    ],
  },
  {
    label: "Customize",
    links: [{ href: "/docs/design-tokens", text: "Design tokens" }],
  },
  {
    label: "Reference",
    links: [{ href: "/docs/registry", text: "How installation works" }],
  },
];

const siteGroups = [
  {
    label: "Explore",
    links: SITE_NAVIGATION_LINKS,
  },
  {
    label: "Project",
    links: [
      { href: "/docs/resources", text: "Resources" },
      { href: "/docs/credits", text: "Credits & license" },
    ],
  },
];

const projectLinks = [
  { href: "/docs/resources", text: "Resources" },
  { href: "/docs/credits", text: "Credits & license" },
];

export function SidebarNav({
  mobileOpen,
  mode = "docs",
  onClose,
}: {
  mobileOpen: boolean;
  mode?: "docs" | "site";
  onClose: () => void;
}) {
  const { path: pathname } = useRouter();
  const sidebar = useRef<HTMLElement>(null);
  const searchInput = useRef<HTMLInputElement>(null);
  const [componentQuery, setComponentQuery] = useState("");
  const navigationLabel = mode === "site" ? "Site navigation" : "Documentation navigation";

  const filteredComponents = useMemo(() => {
    const query = componentQuery.trim().toLowerCase();
    if (!query) return COMPONENT_DIRECTORY_LINKS;

    return COMPONENT_DIRECTORY_LINKS.filter((link) => link.text.toLowerCase().includes(query));
  }, [componentQuery]);

  function isActive(href: string) {
    return isNavigationPathActive(pathname, href);
  }

  const setBackgroundInert = useCallback(
    (inert: boolean) => {
      const selectors =
        mode === "site"
          ? [".site-header", "#main-content"]
          : [".site-header", ".docs-main", ".docs-toc"];

      for (const selector of selectors) {
        document.querySelector<HTMLElement>(selector)?.toggleAttribute("inert", inert);
      }
    },
    [mode],
  );

  const closeAndRestoreFocus = useCallback(() => {
    onClose();
    requestAnimationFrame(() =>
      document.querySelector<HTMLButtonElement>(".mobile-menu-button")?.focus(),
    );
  }, [onClose]);

  const revealActiveLink = useCallback(() => {
    requestAnimationFrame(() => {
      const container = sidebar.current;
      const activeLink = container?.querySelector<HTMLElement>('a[aria-current="page"]');
      if (!container || !activeLink) return;

      const containerRect = container.getBoundingClientRect();
      const activeRect = activeLink.getBoundingClientRect();
      const edgePadding = 24;
      const visible =
        activeRect.top >= containerRect.top + edgePadding &&
        activeRect.bottom <= containerRect.bottom - edgePadding;

      if (!visible) {
        container.scrollTo({
          top:
            container.scrollTop +
            activeRect.top -
            containerRect.top -
            containerRect.height / 2 +
            activeRect.height / 2,
        });
      }
    });
  }, []);

  useEffect(() => {
    const viewport = window.matchMedia("(max-width: 1023px)");

    function onViewportChange(event: MediaQueryListEvent) {
      if (!event.matches && mobileOpen) onClose();
    }

    viewport.addEventListener("change", onViewportChange);
    if (!viewport.matches && mobileOpen) onClose();

    return () => viewport.removeEventListener("change", onViewportChange);
  }, [mobileOpen, onClose]);

  useLayoutEffect(() => {
    const container = sidebar.current;
    document.documentElement.classList.toggle("menu-open", mobileOpen);
    setBackgroundInert(mobileOpen);

    function onKeyDown(event: globalThis.KeyboardEvent) {
      if (event.key === "Escape") {
        event.preventDefault();
        closeAndRestoreFocus();
        return;
      }

      trapTabFocus(event);
    }

    if (mobileOpen && container) {
      // The visible menu must own focus and Escape before the next browser paint.
      container.addEventListener("keydown", onKeyDown);
      if (mode === "docs") searchInput.current?.focus();
      else container.querySelector<HTMLAnchorElement>(".docs-nav a")?.focus();
    }

    return () => {
      container?.removeEventListener("keydown", onKeyDown);
      document.documentElement.classList.remove("menu-open");
      setBackgroundInert(false);
    };
  }, [closeAndRestoreFocus, mobileOpen, mode, setBackgroundInert]);

  useEffect(() => {
    onClose();
    revealActiveLink();
  }, [pathname, onClose, revealActiveLink]);

  return (
    <>
      {mobileOpen && (
        <button
          className="sidebar-scrim"
          type="button"
          aria-label={`Close ${navigationLabel.toLowerCase()}`}
          onClick={closeAndRestoreFocus}
        />
      )}

      <aside
        ref={sidebar}
        className={[
          "docs-sidebar",
          mode === "site" ? "docs-sidebar--site" : "",
          mobileOpen ? "is-open" : "",
        ]
          .filter(Boolean)
          .join(" ")}
        aria-label={navigationLabel}
        role={mobileOpen ? "dialog" : undefined}
        aria-modal={mobileOpen ? true : undefined}
      >
        <div className="docs-sidebar__mobile-head">
          <strong>{mode === "site" ? "Browse site" : "Browse docs"}</strong>
          <button
            className="icon-button"
            type="button"
            aria-label="Close navigation"
            onClick={closeAndRestoreFocus}
          >
            <X aria-hidden="true" size={18} strokeWidth={2.4} />
          </button>
        </div>

        <nav className="docs-nav">
          {mode === "site" ? (
            siteGroups.map((group) => (
              <section key={group.label} className="docs-nav__group">
                <h2>
                  <BookOpen aria-hidden="true" size={13} />
                  {group.label}
                </h2>
                {group.links.map((link) => {
                  const active = isActive(link.href);
                  return (
                    <Link
                      key={link.href}
                      href={link.href}
                      aria-current={active ? "page" : undefined}
                      className={active ? "is-active" : undefined}
                    >
                      {link.text}
                    </Link>
                  );
                })}
              </section>
            ))
          ) : (
            <>
              <section className="docs-nav__group docs-nav__mobile-site">
                <h2>
                  <BookOpen aria-hidden="true" size={13} />
                  Explore site
                </h2>
                {SITE_NAVIGATION_LINKS.map((link) => {
                  const active = isActive(link.href);
                  return (
                    <Link
                      key={link.href}
                      href={link.href}
                      aria-current={active ? "page" : undefined}
                      className={active ? "is-active" : undefined}
                    >
                      {link.text}
                    </Link>
                  );
                })}
              </section>

              {documentGroups.map((group) => (
                <section key={group.label} className="docs-nav__group">
                  <h2>
                    <BookOpen aria-hidden="true" size={13} />
                    {group.label}
                  </h2>
                  {group.links.map((link) => {
                    const active = isActive(link.href);
                    return (
                      <Link
                        key={link.href}
                        href={link.href}
                        aria-current={active ? "page" : undefined}
                        className={active ? "is-active" : undefined}
                      >
                        {link.text}
                      </Link>
                    );
                  })}
                </section>
              ))}

              <section className="docs-nav__group docs-nav__components">
                <div className="docs-nav__group-heading">
                  <h2>
                    <Box aria-hidden="true" size={13} />
                    Components
                  </h2>
                  <span>
                    {filteredComponents.length}/{COMPONENT_DIRECTORY_LINKS.length}
                  </span>
                </div>

                <label className="sidebar-filter">
                  <Search aria-hidden="true" size={14} />
                  <input
                    ref={searchInput}
                    value={componentQuery}
                    type="search"
                    placeholder="Filter components"
                    aria-label="Filter components"
                    onChange={(event) => setComponentQuery(event.target.value)}
                  />
                </label>

                <div className="component-nav-list">
                  {filteredComponents.map((link) => {
                    const active = isActive(link.href);
                    return (
                      <Link
                        key={link.href}
                        href={link.href}
                        aria-current={active ? "page" : undefined}
                        className={active ? "is-active" : undefined}
                      >
                        {link.text}
                      </Link>
                    );
                  })}
                  {filteredComponents.length === 0 && (
                    <p className="component-nav-empty">No matches</p>
                  )}
                </div>
              </section>

              <section className="docs-nav__group">
                <h2>Project</h2>
                {projectLinks.map((link) => {
                  const active = isActive(link.href);
                  return (
                    <Link
                      key={link.href}
                      href={link.href}
                      aria-current={active ? "page" : undefined}
                      className={active ? "is-active" : undefined}
                    >
                      {link.text}
                    </Link>
                  );
                })}
              </section>
            </>
          )}
        </nav>
      </aside>
    </>
  );
}
